import Link from "next/link";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  ArrowLeft,
  ClipboardList,
  LineChart,
  Sparkles,
  Shield,
  ExternalLink,
  CheckCircle,
  AlertTriangle,
} from "lucide-react";

export default function QualityExplainerPage() {
  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div>
        <Link
          href="/app"
          className="text-sm text-muted-foreground hover:text-foreground flex items-center gap-1 mb-4"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </Link>
        <h1 className="text-3xl font-bold tracking-tight">Quality Metrics</h1>
        <p className="text-muted-foreground mt-2 text-lg">
          How CarePilot evaluates every generated plan
        </p>
      </div>

      {/* Overview */}
      <Card className="bg-card/50 border-border/40">
        <CardContent className="pt-6">
          <p className="text-muted-foreground leading-relaxed">
            Every care plan generated by CarePilot is automatically evaluated by AI judges using{" "}
            <a
              href="https://www.comet.com/opik"
              target="_blank"
              rel="noopener noreferrer"
              className="text-primary hover:underline inline-flex items-center gap-1"
            >
              Opik
              <ExternalLink className="w-3 h-3" />
            </a>
            . This ensures plans are not just generated, but validated for quality before you see them.
            All evaluation traces are logged and can be inspected for transparency.
          </p>
        </CardContent>
      </Card>

      {/* Metrics Grid */}
      <div className="space-y-6">
        <h2 className="text-xl font-semibold">Evaluation Criteria</h2>

        <div className="grid md:grid-cols-2 gap-6">
          {/* Actionability */}
          <Card className="border-border/40">
            <CardHeader className="pb-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-blue-500/10 flex items-center justify-center">
                  <ClipboardList className="w-5 h-5 text-blue-400" />
                </div>
                <div>
                  <CardTitle className="text-lg">Actionability</CardTitle>
                  <CardDescription>Score: 1-5</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className="text-sm text-muted-foreground leading-relaxed">
                Measures whether the plan contains specific, concrete actions that can be executed
                immediately without further clarification.
              </p>
              <div className="space-y-2">
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Clear step-by-step instructions</span>
                </div>
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Specific time estimates per action</span>
                </div>
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">No vague or abstract suggestions</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Feasibility */}
          <Card className="border-border/40">
            <CardHeader className="pb-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-green-500/10 flex items-center justify-center">
                  <LineChart className="w-5 h-5 text-green-400" />
                </div>
                <div>
                  <CardTitle className="text-lg">Feasibility</CardTitle>
                  <CardDescription>Score: 1-5</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className="text-sm text-muted-foreground leading-relaxed">
                Evaluates whether the plan can realistically be completed within the caregiver&apos;s
                stated constraints (time, budget, energy, distance).
              </p>
              <div className="space-y-2">
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Respects weekly time availability</span>
                </div>
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Stays within budget limits</span>
                </div>
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Considers distance and energy level</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Empathy Tone */}
          <Card className="border-border/40">
            <CardHeader className="pb-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-purple-500/10 flex items-center justify-center">
                  <Sparkles className="w-5 h-5 text-purple-400" />
                </div>
                <div>
                  <CardTitle className="text-lg">Empathy Tone</CardTitle>
                  <CardDescription>Score: 1-5</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className="text-sm text-muted-foreground leading-relaxed">
                Assesses whether the plan&apos;s language is supportive, understanding, and
                acknowledges the emotional difficulty of caregiving.
              </p>
              <div className="space-y-2">
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Compassionate language throughout</span>
                </div>
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Acknowledges caregiver burden</span>
                </div>
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Encouraging without being dismissive</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Safety */}
          <Card className="border-border/40">
            <CardHeader className="pb-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-red-500/10 flex items-center justify-center">
                  <Shield className="w-5 h-5 text-red-400" />
                </div>
                <div>
                  <CardTitle className="text-lg">Safety</CardTitle>
                  <CardDescription>Verdict: Pass / Fail</CardDescription>
                </div>
              </div>
            </CardHeader>
            <CardContent className="space-y-3">
              <p className="text-sm text-muted-foreground leading-relaxed">
                Checks whether the plan appropriately addresses risk signals and includes necessary
                safety guidance without encouraging harmful actions.
              </p>
              <div className="space-y-2">
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Risk signals are acknowledged</span>
                </div>
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">Emergency resources mentioned if needed</span>
                </div>
                <div className="flex items-start gap-2 text-sm">
                  <CheckCircle className="w-4 h-4 text-green-400 mt-0.5 flex-shrink-0" />
                  <span className="text-muted-foreground">No harmful or dangerous suggestions</span>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Score Interpretation */}
      <Card className="border-border/40">
        <CardHeader>
          <CardTitle className="text-lg">Score Interpretation</CardTitle>
          <CardDescription>Understanding what the numbers mean</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid sm:grid-cols-3 gap-4">
            <div className="p-4 rounded-lg bg-green-500/10 border border-green-500/20">
              <div className="flex items-center gap-2 mb-2">
                <Badge className="bg-green-500/20 text-green-400 hover:bg-green-500/20">4.0 - 5.0</Badge>
              </div>
              <p className="text-sm text-muted-foreground">
                Excellent quality. The plan excels in this dimension.
              </p>
            </div>
            <div className="p-4 rounded-lg bg-yellow-500/10 border border-yellow-500/20">
              <div className="flex items-center gap-2 mb-2">
                <Badge className="bg-yellow-500/20 text-yellow-400 hover:bg-yellow-500/20">3.0 - 3.9</Badge>
              </div>
              <p className="text-sm text-muted-foreground">
                Acceptable quality. Room for improvement but functional.
              </p>
            </div>
            <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/20">
              <div className="flex items-center gap-2 mb-2">
                <Badge className="bg-red-500/20 text-red-400 hover:bg-red-500/20">1.0 - 2.9</Badge>
              </div>
              <p className="text-sm text-muted-foreground">
                Needs improvement. Consider regenerating the plan.
              </p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* How Evaluation Works */}
      <Card className="border-border/40">
        <CardHeader>
          <CardTitle className="text-lg">How Evaluation Works</CardTitle>
          <CardDescription>The three-stage pipeline</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid md:grid-cols-3 gap-4">
            <div className="p-4 rounded-lg bg-muted/30 border border-border/40">
              <Badge variant="outline" className="mb-3">Stage 1</Badge>
              <h4 className="font-medium mb-1">Triage</h4>
              <p className="text-sm text-muted-foreground">
                Analyzes the case context and identifies key challenges.
              </p>
            </div>
            <div className="p-4 rounded-lg bg-muted/30 border border-border/40">
              <Badge variant="outline" className="mb-3">Stage 2</Badge>
              <h4 className="font-medium mb-1">Plan Generation</h4>
              <p className="text-sm text-muted-foreground">
                Creates a structured 7-day plan with goals and actions.
              </p>
            </div>
            <div className="p-4 rounded-lg bg-muted/30 border border-border/40">
              <Badge variant="outline" className="mb-3">Stage 3</Badge>
              <h4 className="font-medium mb-1">Critic Evaluation</h4>
              <p className="text-sm text-muted-foreground">
                AI judges evaluate the plan on all four metrics.
              </p>
            </div>
          </div>

          <div className="flex items-start gap-2 p-4 rounded-lg bg-muted/20 border border-border/40">
            <AlertTriangle className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" />
            <p className="text-sm text-muted-foreground">
              All traces are logged to Opik for transparency and debugging. You can view detailed
              evaluation rationales on each case&apos;s quality page.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
